version: '3.7'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: yuichi110/c8dep_app:v1.0
    depends_on:
    - db
    ports:
    - 8080:80
    environment:
      REDIS_HOST: db
    volumes:
    - ./app/src:/src
  db:
    image: redis:5.0.6-alpine3.10
