apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    pod: app
  ports:
  - port: 80
    targetPort: http
    nodePort: 30000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    pod: app
spec:
  containers:
  - name: app
    image: yuichi110/c8dep_app:v1.0
    ports:
    - name: http
      containerPort: 80
    env:
    - name: REDIS_HOST
      value: db
