apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    pod: db
  ports:
  - port: 6379
    targetPort: redis
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    pod: db
spec:
  containers:
  - name: db
    image: redis:5.0.6-alpine3.10
    ports:
    - name: redis
      containerPort: 6379
